server:
  port: 8100
spring:
  application:
    name: gaming-server-web-admin
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html
dubbo:
  application:
    id: gaming-server-web-admin
    name: gaming-server-web-admin
  scan:
    base-packages: com.ooqiu.gaming.server.web.admin
  protocol:
    id: dubbo
    name: dubbo
    port: 20880
  registry:
    id: zookeeper
    address: zookeeper://192.168.17.130:2181?backup=192.168.17.130:2182,192.168.17.130:2183